import type { Metadata } from "next";
import { DM_Sans, Geist_Mono, Inter, Zain } from "next/font/google";
import Providers from "@/components/providers";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { hasLocale } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { cn } from "@/lib/utils";

/** Arabic — Zain (Google Fonts) */
const zain = Zain({
  subsets: ["arabic"],
  variable: "--font-zain",
  weight: ["400", "700", "800"],
});

/** English — Inter (readable UI) */
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-en",
  weight: ["400", "500", "600", "700"],
});

/** French — DM Sans (Latin + clean UI) */
const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-fr",
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  const localeBodyFont =
    locale === "ar"
      ? zain.className
      : locale === "fr"
        ? dmSans.className
        : inter.className;

  const fontSansBody =
    locale === "ar"
      ? "var(--font-zain), system-ui, sans-serif"
      : locale === "fr"
        ? "var(--font-fr), ui-sans-serif, system-ui, sans-serif"
        : "var(--font-en), ui-sans-serif, system-ui, sans-serif";

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      className={cn(
        "h-full antialiased",
        zain.variable,
        inter.variable,
        dmSans.variable,
        geistMono.variable,
        localeBodyFont,
      )}
      style={{ "--font-sans-body": fontSansBody } as React.CSSProperties}
    >
      <body>
        <Providers>
          <div className="flex min-h-screen min-w-0 flex-col overflow-x-hidden">
            <Header />
            <main className="min-w-0 flex flex-1 flex-col">{children}</main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
